
-- CONFERIR TAMANHO DA BASE  E SE HA DADOS REPETIDOS
SELECT DISTINCT * FROM RouboVeiculos

SELECT DISTINCT(NUM_BO)FROM RouboVeiculos

SELECT NUM_BO
FROM RouboVeiculos
GROUP BY NUM_BO
HAVING COUNT(*) > 1;


-- EXCLUSAO DE COLUNAS IRRELEVANTES
ALTER TABLE RouboVeiculos
DROP COLUMN FAIXA_DIA_MES

ALTER TABLE RouboVeiculos
DROP COLUMN F37

ALTER TABLE RouboVeiculos
DROP COLUMN F38


--*****************************************////////////////********************************
-- ANÁLISES


-- QTD ROUBOS POR BAIRRO E % DE CADA BAIRRO (TOP 10)
SELECT TOP(10)
	DENSE_RANK() OVER(ORDER BY COUNT(*) DESC) AS 'RANK',
    BAIRRO,
    COUNT(*) AS 'QTD ROUBOS/BAIRRO',
	SUM(COUNT(*)) OVER () AS 'TOTAL ROUBOS',
	CONCAT(FORMAT(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 'N2'), ' %') AS '% BAIRRO'
FROM RouboVeiculos
WHERE BAIRRO IS NOT NULL
GROUP BY BAIRRO

/*OUTPUT>

RANK		BAIRRO		QTD ROUBOS/BAIRRO	TOTAL ROUBOS	% BAIRRO
	1		CENTRO			40						1683	2,38 %
	2		SAO MATEUS		29						1683	1,72 %
	3		CAPAO REDONDO	20						1683	1,19 %
	4		IPIRANGA		19						1683	1,13 %
	4		SAUDE			19						1683	1,13 %
	5		ITAQUERA		18						1683	1,07 %
	6		CAMPO LIMPO		17						1683	1,01 %
	7		SACOMA			16						1683	0,95 %
	7		SANTO AMARO		16						1683	0,95 %
	8		PEDREIRA		13						1683	0,77 %
*/













-- QTD ROUBOS POR CIDADE E % DE CADA CIDADE(TOP 10)
SELECT TOP(10)
	DENSE_RANK() OVER(ORDER BY COUNT(*) DESC) AS 'RANK',
    CIDADE,
    COUNT(*) AS 'QTD ROUBOS/CIDADE',
	SUM(COUNT(*)) OVER () AS 'TOTAL_ROUBOS',
    CONCAT(FORMAT(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 'N2'), ' %') AS '% POR CIDADE'
FROM RouboVeiculos
WHERE CIDADE IS NOT NULL
GROUP BY CIDADE




-- ANALISE ROUBO POR MES E EVOLUÇÃO TEMPORAL NO ANO DE 2023
WITH CTE_RouboVeiculos AS (
    SELECT
        YEAR(DATAOCORRENCIA) AS ANO,
        MES,
        COUNT(*) AS QTD_ROUBOS
    FROM RouboVeiculos
    WHERE YEAR(DATAOCORRENCIA) = 2023 AND MES IS NOT NULL AND MES IN (1,2,3,4,5,6,7,8,9,10,11,12)
    GROUP BY YEAR(DATAOCORRENCIA), MES
)

SELECT
    ANO,
    MES,
    QTD_ROUBOS AS 'QTD ROUBOS/MES',
    LAG(QTD_ROUBOS) OVER (ORDER BY MES) AS 'MES ANTERIOR',
    CONCAT(
        CASE WHEN (QTD_ROUBOS * 1.0 / LAG(QTD_ROUBOS) OVER (ORDER BY MES) - 1) > 0 THEN 'AUMENTO EM '
             WHEN (QTD_ROUBOS * 1.0 / LAG(QTD_ROUBOS) OVER (ORDER BY MES) - 1) < 0 THEN 'QUEDA EM ' 
			 ELSE '0'
        END,
        ' ',
        FORMAT((QTD_ROUBOS * 1.0 / LAG(QTD_ROUBOS) OVER (ORDER BY MES) - 1), '0.00%') + ' DOS CASOS'
    ) AS 'VARIAÇÃO MES'
FROM CTE_RouboVeiculos;







-- DIAS DA SEMANA COM MAIOR INCIDÊNCIA DE ROUBOS E PORCENTAGEM
SELECT 
	DATENAME(WEEKDAY, DATAOCORRENCIA) AS 'DIA DA SEMANA', 
	COUNT(*) AS 'QTD ROUBOS',
	CAST((COUNT(*) * 100.0 / (SELECT COUNT(*) FROM [dbo].[RouboVeiculos])) AS DECIMAL(10, 2)) AS '%  DIA'
FROM [dbo].[RouboVeiculos]
GROUP BY DATENAME(WEEKDAY, DATAOCORRENCIA)
ORDER BY 'QTD ROUBOS' DESC







-- TOP10 HORARIOS COM MAIOR QTD ROUBOS
SELECT TOP(10) 
	CONCAT(DATEPART(HOUR, HORAOCORRENCIA) ,' HORAS') AS HORARIO , 
	COUNT(*) AS TOTAL_ROUBOS
FROM RouboVeiculos
WHERE HORAOCORRENCIA IS NOT NULL
GROUP BY DATEPART(HOUR, HORAOCORRENCIA)
ORDER BY TOTAL_ROUBOS DESC



-- TOP(10) MARCAS E MODELOS COM MAIOR QUANTIDADE DE ROUBOS
SELECT TOP(10)
	MARCA, 
	MODELO, 
	COUNT(*) AS QTD_ROUBOS
FROM [dbo].[RouboVeiculos]
GROUP BY MARCA, MODELO
ORDER BY QTD_ROUBOS DESC;



-- ROUBOS POR DESCRIÇÃO TIPO DE VEICULO
SELECT 
	DESCR_TIPO_VEICULO, 
	COUNT(*) AS Total_Roubos
FROM [dbo].[RouboVeiculos]
WHERE DESCR_TIPO_VEICULO IS NOT NULL
GROUP BY DESCR_TIPO_VEICULO
ORDER BY Total_Roubos DESC;


-- TOP10 LOCAIS COM MAIOR INCIDENCIA
SELECT TOP(10)
    DESCRICAOLOCAL,
    COUNT(*) AS QTD_ROUBOS,
    CONCAT(CAST(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM RouboVeiculos WHERE DESCRICAOLOCAL IS NOT NULL) AS DECIMAL(10, 2)), '%') AS PORCENTAGEM
FROM RouboVeiculos
WHERE DESCRICAOLOCAL IS NOT NULL
GROUP BY DESCRICAOLOCAL
ORDER BY QTD_ROUBOS DESC



-- %  FLAGRANTES
SELECT
    FLAGRANTE,
    COUNT(*) AS QTD_ROUBO,
    CONCAT(CAST(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM RouboVeiculos) AS DECIMAL(10, 2)), '%') AS PORCENTAGEM
FROM RouboVeiculos
GROUP BY FLAGRANTE



-- TOP10 ROUBOS POR COR DE VEICULOS
SELECT TOP(10)
	DESCR_COR_VEICULO,
	COUNT(*) AS 'QTD_ROUBOS',
	SUM(COUNT(*)) OVER() AS 'TOTAL_ROUBOS',
	CONCAT(CAST(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM RouboVeiculos) AS DECIMAL(10, 2)), '%') AS '%'
FROM RouboVeiculos
GROUP BY DESCR_COR_VEICULO
ORDER BY QTD_ROUBOS DESC





-- TOP10 DELEGACIAS DE ATENDIMENTO
WITH AnaliseDelegacias AS (
    SELECT TOP(10)
        DELEGACIA_NOME,
        COUNT(*) AS QTD_ROUBOS,
        DENSE_RANK() OVER (ORDER BY COUNT(*) DESC) AS RANK
    FROM RouboVeiculos
    WHERE YEAR(DATAOCORRENCIA) = 2023
    GROUP BY DELEGACIA_NOME
)

SELECT
    DELEGACIA_NOME,
    QTD_ROUBOS,
    RANK
FROM AnaliseDelegacias
ORDER BY RANK;




-- TOP5 SOLUÇÃO DOS CASOS
WITH AnaliseResolucao AS (
    SELECT TOP(5)
        SOLUCAO,
        COUNT(*) AS QTD_ROUBOS
    FROM [dbo].[RouboVeiculos]
    WHERE YEAR(DATAOCORRENCIA) = 2023 AND SOLUCAO IS NOT NULL
    GROUP BY SOLUCAO
)

SELECT
    SOLUCAO,
    QTD_ROUBOS,
    FORMAT((QTD_ROUBOS * 100.0 / SUM(QTD_ROUBOS) OVER ()), 'N2') AS '%'
FROM AnaliseResolucao
ORDER BY QTD_ROUBOS DESC;





